apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops

resources:
#- ocpvirt.yaml
- ../../base/
- gitops-rbac.yaml

patchesStrategicMerge:
#- datavolumes-application.yaml
- vms-application.yaml
#- win2k19-application.yaml
