apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostpath-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: hostpath-provisioner
    server: https://kubernetes.default.svc
  project: default
  source:
    path: hpp
    repoURL: https://github.com/tosin2013/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
