apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-gitops
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/overlays/kubernetes
    repoURL: https://github.com/tosin2013/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
